title: Toko Online Kamu
description: Website toko online seperti Shopee menggunakan GitHub Pages
theme: null   # Tidak pakai tema Jekyll bawaan
markdown: kramdown

# Aktifkan folder assets
include:
  - assets
  - pages
